### Crear alumno
POST http://localhost:1234/students
Content-Type: application/json

{
  "name": "Santino",
  "lastName":"Stimoli",
  "graduation": "negro (III)",
  "phone": 1134310411,
  "birthday": "04-11-2003",
  "startDate": "??-03-2010"
}

### Modificar alumno
PATCH http://localhost:1234/students/2
Content-Type: application/json

{
  "name": "aaa",
  "lastName": "aaa",
  "phone": 1234567890
}

### Cambiar actividad
PATCH http://localhost:1234/students/changeActivitie/8

### Eliminar alumno
DELETE  http://localhost:1234/students/8