### Obtener todos los alumnos
GET http://localhost:1234/students

### Obtener alumno por ID
GET http://localhost:1234/students/1

### Filtrar alumnos por graduación
GET http://localhost:1234/students?graduation=blanco

### Filtrar alumnos por actividad
GET http://localhost:1234/students?actives=true

### Filtrar alumnos por actividad y graduación
GET http://localhost:1234/students?actives=false&graduation=verde